import OrderItem from '@components/OrderItem';
import '@styles/Orders.scss';                /*@styles*/ //! (@) => @styles

try{	
let arr = [0,1,2,3,4,5,6,7,8,9];  
let array = [0,1];  
let n = arr;
console.log(n.map( (e) => {
  const phi = 1.6162;
  const parte1 = phi*e;
  const parte2 = (1-phi)*e;
  const multi = parte1 - parte2;
  const divi = Math.sqrt(4);
  const wtf = (multi/divi);
  return wtf.toFixed(4);
}));

for(let i = 0 ; i<=10; i++) {

  const wtf = arr.map((ac,i,arr) => {
    const aja = ac-1+ac-2+i;
    return aja <= 0 ? arr.shift() : aja;
  });  
  console.log((wtf =>wtf[i-1]+wtf[i-2])(wtf),"()=%$/&%WERUFVKSDMAH&$%||>");
  };

  var lambo = 10;
  var ffibo=[0,1];
  for(let i=2; i<lambo ; i++){ 
    let a = ffibo.push(ffibo[i-1]+ffibo[i-2])
    console.log("fibbonacchi ()=>",ffibo[i],ffibo);
  }
  for(let i = 2 ; i<=10; i++) {
  const quetal = array.push(array[i-1]+array[i-2]);  
  console.log("FSDCAMILATHIHIIYOI(%&%==>", array[i],array, "<==FS)DFGUTIERREZIYOI(%&%");
  console.log("uhuYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZYTCAMILAGUTTIERREZdg","$/&%&$%>");
  };

} catch(e) {	
  console.error(e.stack,'\n[*] '+e.name,'\n[*] '+e.message)
};

const Orders =()=> { return (
<div className="Orders">
<div className="Orders-container">
  <h1 className="title-orders">My orders</h1>
  <div className="Orders-content">
    <OrderItem />
  </div>
</div>
</div>
); }; export default Orders;